name: adventuresmith_template_engine
description: A template engine for Dart version of Adventuresmith
version: 0.0.1
homepage: https://github.com/stevesea/adventuresmith_template_engine
authors:
  - steve christensen <adventuresmith.rpg@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dart_dice_parser: ^2.0.1
  dart_collection_sampler: ^2.0.1
  logging: ^0.11.4
  petitparser: ^2.4.0

dev_dependencies:
  test: ^1.12.0
  mockito: ^4.1.0
  args: ^1.5.2
