name: adventuresmith_template_engine
description: A template engine for Dart version of Adventuresmith
version: 0.0.1
homepage: https://github.com/stevesea/adventuresmith_template_engine
authors:
  - steve christensen <adventuresmith.rpg@gmail.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  dart_dice_parser: ^1.3.4
  dart_collection_sampler: ^1.0.3
  logging: ^0.11.3+2
  petitparser: ^2.3.0

dev_dependencies:
  test: ^1.6.4
  mockito: ^4.1.0
  args: ^1.5.2
